In [2]:
import numpy as np

In [3]:
length = np.array([280/3, 278/3, 250/8, 224/7, 266/18])

In [8]:
sinuses =  (length)/np.sqrt(np.square(length) + 1254**2)

In [13]:
532*10**-9/sinuses * 10**6

array([ 7.16757064,  7.21885283, 21.35472376, 20.85453677, 45.14713457])

In [19]:
delta_x = (3 * 1254**2) / ( np.sqrt(np.square(length) + 1254**2) * np.square(length))
delta_a = (5 * 1254) / ( np.sqrt(np.square(length) + 1254**2) * np.square(length))

In [21]:
sigma = 532*10**-6 * np.sqrt(np.square(delta_a) + np.square(delta_x))

In [1]:
np.asin(sinuses) * 100


NameError: name 'np' is not defined

In [7]:
a_1 = np.array([160, 160, 165, 169])
a_2 = 25
ba = np.array([524, 524, 519, 515])
b_2 = 585
d_proj = np.array([0.625, 0.667, 2, 2])

In [8]:
g = (ba - a_2)*b_2/(a_2*a_1)
np.round(g, 2)

array([72.98, 72.98, 70.06, 67.85])

In [11]:
np.round(d_proj * g * np.sqrt((0.2/16)**2 + np.square(8/b_2) + np.square(8/a_1) + np.square(8/ba)), 2)

array([2.53, 2.7 , 7.59, 7.21])